"""soft delete questions + attempt snapshot

Revision ID: 3a2437032600
Revises: 9fa0bb8cd047
Create Date: 2026-05-08 17:09:19.408175

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2437032600'
down_revision: str | None = '9fa0bb8cd047'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attempt_questions',
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('attempt_id', 'question_id', name='uq_attempt_question')
    )
    op.create_index(op.f('ix_attempt_questions_attempt_id'), 'attempt_questions', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_questions_question_id'), 'attempt_questions', ['question_id'], unique=False)
    op.add_column('questions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_questions_deleted_at'), 'questions', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questions_deleted_at'), table_name='questions')
    op.drop_column('questions', 'deleted_at')
    op.drop_index(op.f('ix_attempt_questions_question_id'), table_name='attempt_questions')
    op.drop_index(op.f('ix_attempt_questions_attempt_id'), table_name='attempt_questions')
    op.drop_table('attempt_questions')
    # ### end Alembic commands ###
